#!/bin/sh

ARCH="amd64 386"
OS="windows linux darwin"
cat > ../pick/vers.go <<VVVV
package main
const VERS = "GRAPH`9 date -n`"
VVVV
(cd ../pick; go build)

go env > /tmp/vars.$$
. /tmp/vars.$$

for ar in $ARCH; do
	export GOARCH=$ar
	for sysos in $OS; do
		CGO_ENABLED=1
		export GOOS=$sysos
		if [ "$GOOS" != "darwin" ]
		then
			export CGO_ENABLED=0
		fi
		cd ../pick
		go install
		cd ../Install
		cd ../pam
		go install
		cd ../Install
	done
done
. /tmp/vars.$$

for mach in $ARCH; do
	echo mach is $mach
	for sysos in $OS; do
		echo building installer for $mach $sysos
		cd $sysos
		export mach
		export sysos
		make
		cd ..
	done
done
