#!/bin/sh

TAR=`which gtar`
mkdir -p falsetar

cat > falsetar/tar <<EEO
#!/bin/sh
"$TAR".good --owner=root --group=root \$*
EEO
chmod +x falsetar/tar

cp $TAR "$TAR".$$
mv $TAR "$TAR".good
cp falsetar/tar $TAR

dpkg-deb -b $1 $2
rm -r falsetar
mv "$TAR".$$ $TAR

