#!/bin/sh

if [ $# -ne 1 ]
then
	echo usage: file.deb 1>&2
	exit 1
fi

name=$1
echo name is $name
dpkg-deb -x "$name" picky
dpkg-deb -e "$name" picky/DEBIAN
mv $name "$name".old
fakeroot bash -c "cd picky; chown -R root *; chgrp -R root *; cd ..; dpkg-deb -b picky $name"
